In [1]:
import numpy as np

In [7]:
#initalize array
a = np.array([1, 2, 3])
print(a)

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=float)
print(b)

[1 2 3]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [11]:
#dimension of the array
print(a.ndim)
print(b.ndim)

#shape of the array (row x column)
print(a.shape)
print(b.shape)

#type
print(a.dtype)
print(b.dtype)

#size
print(a.itemsize)
print(b.itemsize)

#total size
print(a.nbytes)
print(b.nbytes)

1
2
(3,)
(2, 4)
int64
float64
8
8
24
64


In [ ]:
#array manipulation

#get specific element [row, column]
print(b[1,3])

#get specific row
print(b[1,:])

#specific column
print(b[:,3])

#[start:end:step]
print(b[0, 1:4:2])

8.0
[5. 6. 7. 8.]
[4. 8.]
[2. 4.]


In [25]:
#all 0's
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
#all 1's
np.ones((2, 3, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [26]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])